version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname:   zookeeper
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka1
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka1:29092

#  schema_registry:
#    image: confluentinc/cp-schema-registry:latest
#    hostname: schema_registry
#    container_name: schema_registry
#    networks:
#      - broker-kafka
#    depends_on:
#      - zookeeper
#      - kafka1
#    ports:
#      - "8081:8081"
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: schema_registry
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:29092
#      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
#      SCHEMA_REGISTRY_KAFKASTORE_LISTENERS: http://0.0.0.0:8081
#      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
#      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,DELETE,OPTIONS
#      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"

#  schema-registry-ui:
#    image: landoop/schema-registry-ui
#    hostname: schema-registry-ui
#    restart: always
#    networks:
#      - broker-kafka
#    depends_on:
#      - schema_registry
#    ports:
#      - "8000:8000"
#    environment:
#      SCHEMAREGISTRY_URL: http://schema_registry:8081
#      PROXY: "true"

networks:
  broker-kafka:
    driver: bridge